"""Add display_name to users table

Revision ID: 546754fe9bea
Revises: 2d47c72d6697
Create Date: 2025-08-17 17:25:17.370359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "546754fe9bea"
down_revision: Union[str, None] = "2d47c72d6697"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "commands", sa.Column("environment", sa.Text(), nullable=True)
    )
    op.add_column(
        "commands", sa.Column("timeout_seconds", sa.Integer(), nullable=True)
    )
    op.add_column(
        "commands",
        sa.Column(
            "capture_output",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
    )
    op.add_column("commands", sa.Column("stdout", sa.Text(), nullable=True))
    op.add_column("commands", sa.Column("stderr", sa.Text(), nullable=True))
    op.add_column(
        "commands",
        sa.Column(
            "output_truncated",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column(
        "commands",
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "commands",
        sa.Column(
            "is_dangerous",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    op.add_column("commands", sa.Column("pid", sa.Integer(), nullable=True))
    op.add_column(
        "commands", sa.Column("signal", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "commands", sa.Column("sequence_number", sa.Integer(), nullable=True)
    )
    op.add_column(
        "commands", sa.Column("parent_command_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "sessions", sa.Column("environment", sa.Text(), nullable=True)
    )
    op.add_column(
        "sessions", sa.Column("error_message", sa.Text(), nullable=True)
    )
    op.add_column(
        "ssh_profiles",
        sa.Column(
            "last_connection_status", sa.String(length=50), nullable=True
        ),
    )
    op.add_column(
        "ssh_profiles",
        sa.Column(
            "last_connection_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "ssh_profiles",
        sa.Column(
            "last_successful_connection_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "ssh_profiles",
        sa.Column("last_error_message", sa.Text(), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("display_name", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "display_name")
    op.drop_column("ssh_profiles", "last_error_message")
    op.drop_column("ssh_profiles", "last_successful_connection_at")
    op.drop_column("ssh_profiles", "last_connection_at")
    op.drop_column("ssh_profiles", "last_connection_status")
    op.drop_column("sessions", "error_message")
    op.drop_column("sessions", "environment")
    op.drop_column("commands", "parent_command_id")
    op.drop_column("commands", "sequence_number")
    op.drop_column("commands", "signal")
    op.drop_column("commands", "pid")
    op.drop_column("commands", "is_dangerous")
    op.drop_column("commands", "executed_at")
    op.drop_column("commands", "output_truncated")
    op.drop_column("commands", "stderr")
    op.drop_column("commands", "stdout")
    op.drop_column("commands", "capture_output")
    op.drop_column("commands", "timeout_seconds")
    op.drop_column("commands", "environment")
    # ### end Alembic commands ###
